### PR TITLE
Added Search Vehicle and struct

### PR DESCRIPTION
**Pull request by Bob2038**
We added searchVehicle. More info in the comments. Added a struct that we needed for searchVehicle.

### CODE REVIEW

**Review by stevenBhub — CHANGES_REQUESTED** [review]
Did you create your own Vehical.h and Main.cpp file?

There could be issues merging this file because the systems is not recognizing your changes vs the original file. 

Perhaps you need to pull the new versions of the files and add your code then create a new main push request? We can discuss.

The code looks great.

**Comment by sparkdragon586** [comment]
I can merge the files in I'm currently working on a commit to manually merge them.

**Comment by stevenBhub** [comment]
> I can merge the files in I'm currently working on a commit to manually merge them.

Good luck, I will work with some groups tomorrow to make sure I understand there code.

**Review by sparkdragon586 — APPROVED** [review]
merging.

**Review by stevenBhub — APPROVED** [review]

**Pull request merged**
